networks:
  gitea:
    external: false

services:
  server:
    image: docker.m.daocloud.io/gitea/gitea:latest
    container_name: gitea-server
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
      - GITEA__server__SSH_PORT=36002
      - GITEA__service__DISABLE_REGISTRATION=true
    restart: always
    networks:
      - gitea
    volumes:
      - /mnt/nas/Public/gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "36001:3000"
      - "36002:22"
    depends_on:
      - db

  db:
    image: docker.m.daocloud.io/library/mysql:latest
    container_name: gitea-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    networks:
      - gitea
    volumes:
      - /mnt/nas/Public/gitea/mysql:/var/lib/mysql
    ports:
      - "36003:3306"
